#pragma once

#define GET_ID(element_name) (element_name##_ID)
#define GET_TYPE(element_name) (element_name##_TYPE)

// Element specification
#define EBML_ID (0x1a45dfa3)
#define EBML_TYPE (Master)
#define EBMLVersion_ID (0x4286)
#define EBMLVersion_TYPE (uint64_t)
#define EBMLReadVersion_ID (0x42f7)
#define EBMLReadVersion_TYPE (uint64_t)
#define DocType_ID (0x4282)
#define DocType_TYPE (string)
#define DocTypeVersion_ID (0x4287)
#define DocTypeVersion_TYPE (uint64_t)
#define DocTypeReadVersion_ID (0x4285)
#define DocTypeReadVersion_TYPE (uint64_t)
#define DocTypeExtension_ID (0x4281)
#define DocTypeExtension_TYPE (Master)
#define DocTypeExtensionName_ID (0x4283)
#define DocTypeExtensionName_TYPE (string)
#define DocTypeExtensionVersion_ID (0x4284)
#define DocTypeExtensionVersion_TYPE (uint64_t)
#define CRC_32_ID (0xbf)
#define CRC_32_TYPE (Binary)
#define Void_ID (0xec)
#define Void_TYPE (Binary)
#define EBMLMaxIDLength_ID (0x42f2)
#define EBMLMaxIDLength_TYPE (uint64_t)
#define EBMLMaxSizeLength_ID (0x42f3)
#define EBMLMaxSizeLength_TYPE (uint64_t)
#define Segment_ID (0x18538067)
#define Segment_TYPE (Master)
#define SeekHead_ID (0x114d9b74)
#define SeekHead_TYPE (Master)
#define Seek_ID (0x4dbb)
#define Seek_TYPE (Master)
#define SeekID_ID (0x53ab)
#define SeekID_TYPE (Binary)
#define SeekPosition_ID (0x53ac)
#define SeekPosition_TYPE (uint64_t)
#define Info_ID (0x1549a966)
#define Info_TYPE (Master)
#define SegmentUID_ID (0x73a4)
#define SegmentUID_TYPE (Binary)
#define SegmentFilename_ID (0x7384)
#define SegmentFilename_TYPE (string)
#define PrevUID_ID (0x3cb923)
#define PrevUID_TYPE (Binary)
#define PrevFilename_ID (0x3c83ab)
#define PrevFilename_TYPE (string)
#define NextUID_ID (0x3eb923)
#define NextUID_TYPE (Binary)
#define NextFilename_ID (0x3e83bb)
#define NextFilename_TYPE (string)
#define SegmentFamily_ID (0x4444)
#define SegmentFamily_TYPE (Binary)
#define ChapterTranslate_ID (0x6924)
#define ChapterTranslate_TYPE (Master)
#define ChapterTranslateID_ID (0x69a5)
#define ChapterTranslateID_TYPE (Binary)
#define ChapterTranslateCodec_ID (0x69bf)
#define ChapterTranslateCodec_TYPE (uint64_t)
#define ChapterTranslateEditionUID_ID (0x69fc)
#define ChapterTranslateEditionUID_TYPE (uint64_t)
#define TimestampScale_ID (0x2ad7b1)
#define TimestampScale_TYPE (uint64_t)
#define Duration_ID (0x4489)
#define Duration_TYPE (float_t)
#define DateUTC_ID (0x4461)
#define DateUTC_TYPE (Date)
#define Title_ID (0x7ba9)
#define Title_TYPE (string)
#define MuxingApp_ID (0x4d80)
#define MuxingApp_TYPE (string)
#define WritingApp_ID (0x5741)
#define WritingApp_TYPE (string)
#define Cluster_ID (0x1f43b675)
#define Cluster_TYPE (Master)
#define Timestamp_ID (0xe7)
#define Timestamp_TYPE (uint64_t)
#define SilentTracks_ID (0x5854)
#define SilentTracks_TYPE (Master)
#define SilentTrackNumber_ID (0x58d7)
#define SilentTrackNumber_TYPE (uint64_t)
#define Position_ID (0xa7)
#define Position_TYPE (uint64_t)
#define PrevSize_ID (0xab)
#define PrevSize_TYPE (uint64_t)
#define SimpleBlock_ID (0xa3)
#define SimpleBlock_TYPE (Binary)
#define BlockGroup_ID (0xa0)
#define BlockGroup_TYPE (Master)
#define Block_ID (0xa1)
#define Block_TYPE (Binary)
#define BlockVirtual_ID (0xa2)
#define BlockVirtual_TYPE (Binary)
#define BlockAdditions_ID (0x75a1)
#define BlockAdditions_TYPE (Master)
#define BlockMore_ID (0xa6)
#define BlockMore_TYPE (Master)
#define BlockAddID_ID (0xee)
#define BlockAddID_TYPE (uint64_t)
#define BlockAdditional_ID (0xa5)
#define BlockAdditional_TYPE (Binary)
#define BlockDuration_ID (0x9b)
#define BlockDuration_TYPE (uint64_t)
#define ReferencePriority_ID (0xfa)
#define ReferencePriority_TYPE (uint64_t)
#define ReferenceBlock_ID (0xfb)
#define ReferenceBlock_TYPE (int64_t)
#define ReferenceVirtual_ID (0xfd)
#define ReferenceVirtual_TYPE (int64_t)
#define CodecState_ID (0xa4)
#define CodecState_TYPE (Binary)
#define DiscardPadding_ID (0x75a2)
#define DiscardPadding_TYPE (int64_t)
#define Slices_ID (0x8e)
#define Slices_TYPE (Master)
#define TimeSlice_ID (0xe8)
#define TimeSlice_TYPE (Master)
#define LaceNumber_ID (0xcc)
#define LaceNumber_TYPE (uint64_t)
#define FrameNumber_ID (0xcd)
#define FrameNumber_TYPE (uint64_t)
#define BlockAdditionID_ID (0xcb)
#define BlockAdditionID_TYPE (uint64_t)
#define Delay_ID (0xce)
#define Delay_TYPE (uint64_t)
#define SliceDuration_ID (0xcf)
#define SliceDuration_TYPE (uint64_t)
#define ReferenceFrame_ID (0xc8)
#define ReferenceFrame_TYPE (Master)
#define ReferenceOffset_ID (0xc9)
#define ReferenceOffset_TYPE (uint64_t)
#define ReferenceTimestamp_ID (0xca)
#define ReferenceTimestamp_TYPE (uint64_t)
#define EncryptedBlock_ID (0xaf)
#define EncryptedBlock_TYPE (Binary)
#define Tracks_ID (0x1654ae6b)
#define Tracks_TYPE (Master)
#define TrackEntry_ID (0xae)
#define TrackEntry_TYPE (Master)
#define TrackNumber_ID (0xd7)
#define TrackNumber_TYPE (uint64_t)
#define TrackUID_ID (0x73c5)
#define TrackUID_TYPE (uint64_t)
#define TrackType_ID (0x83)
#define TrackType_TYPE (uint64_t)
#define FlagEnabled_ID (0xb9)
#define FlagEnabled_TYPE (uint64_t)
#define FlagDefault_ID (0x88)
#define FlagDefault_TYPE (uint64_t)
#define FlagForced_ID (0x55aa)
#define FlagForced_TYPE (uint64_t)
#define FlagHearingImpaired_ID (0x55ab)
#define FlagHearingImpaired_TYPE (uint64_t)
#define FlagVisualImpaired_ID (0x55ac)
#define FlagVisualImpaired_TYPE (uint64_t)
#define FlagTextDescriptions_ID (0x55ad)
#define FlagTextDescriptions_TYPE (uint64_t)
#define FlagOriginal_ID (0x55ae)
#define FlagOriginal_TYPE (uint64_t)
#define FlagCommentary_ID (0x55af)
#define FlagCommentary_TYPE (uint64_t)
#define FlagLacing_ID (0x9c)
#define FlagLacing_TYPE (uint64_t)
#define MinCache_ID (0x6de7)
#define MinCache_TYPE (uint64_t)
#define MaxCache_ID (0x6df8)
#define MaxCache_TYPE (uint64_t)
#define DefaultDuration_ID (0x23e383)
#define DefaultDuration_TYPE (uint64_t)
#define DefaultDecodedFieldDuration_ID (0x234e7a)
#define DefaultDecodedFieldDuration_TYPE (uint64_t)
#define TrackTimestampScale_ID (0x23314f)
#define TrackTimestampScale_TYPE (float_t)
#define TrackOffset_ID (0x537f)
#define TrackOffset_TYPE (int64_t)
#define MaxBlockAdditionID_ID (0x55ee)
#define MaxBlockAdditionID_TYPE (uint64_t)
#define BlockAdditionMapping_ID (0x41e4)
#define BlockAdditionMapping_TYPE (Master)
#define BlockAddIDValue_ID (0x41f0)
#define BlockAddIDValue_TYPE (uint64_t)
#define BlockAddIDName_ID (0x41a4)
#define BlockAddIDName_TYPE (string)
#define BlockAddIDType_ID (0x41e7)
#define BlockAddIDType_TYPE (uint64_t)
#define BlockAddIDExtraData_ID (0x41ed)
#define BlockAddIDExtraData_TYPE (Binary)
#define Name_ID (0x536e)
#define Name_TYPE (string)
#define Language_ID (0x22b59c)
#define Language_TYPE (string)
#define LanguageIETF_ID (0x22b59d)
#define LanguageIETF_TYPE (string)
#define CodecID_ID (0x86)
#define CodecID_TYPE (string)
#define CodecPrivate_ID (0x63a2)
#define CodecPrivate_TYPE (Binary)
#define CodecName_ID (0x258688)
#define CodecName_TYPE (string)
#define AttachmentLink_ID (0x7446)
#define AttachmentLink_TYPE (uint64_t)
#define CodecSettings_ID (0x3a9697)
#define CodecSettings_TYPE (string)
#define CodecInfoURL_ID (0x3b4040)
#define CodecInfoURL_TYPE (string)
#define CodecDownloadURL_ID (0x26b240)
#define CodecDownloadURL_TYPE (string)
#define CodecDecodeAll_ID (0xaa)
#define CodecDecodeAll_TYPE (uint64_t)
#define TrackOverlay_ID (0x6fab)
#define TrackOverlay_TYPE (uint64_t)
#define CodecDelay_ID (0x56aa)
#define CodecDelay_TYPE (uint64_t)
#define SeekPreRoll_ID (0x56bb)
#define SeekPreRoll_TYPE (uint64_t)
#define TrackTranslate_ID (0x6624)
#define TrackTranslate_TYPE (Master)
#define TrackTranslateTrackID_ID (0x66a5)
#define TrackTranslateTrackID_TYPE (Binary)
#define TrackTranslateCodec_ID (0x66bf)
#define TrackTranslateCodec_TYPE (uint64_t)
#define TrackTranslateEditionUID_ID (0x66fc)
#define TrackTranslateEditionUID_TYPE (uint64_t)
#define Video_ID (0xe0)
#define Video_TYPE (Master)
#define FlagInterlaced_ID (0x9a)
#define FlagInterlaced_TYPE (uint64_t)
#define FieldOrder_ID (0x9d)
#define FieldOrder_TYPE (uint64_t)
#define StereoMode_ID (0x53b8)
#define StereoMode_TYPE (uint64_t)
#define AlphaMode_ID (0x53c0)
#define AlphaMode_TYPE (uint64_t)
#define OldStereoMode_ID (0x53b9)
#define OldStereoMode_TYPE (uint64_t)
#define PixelWidth_ID (0xb0)
#define PixelWidth_TYPE (uint64_t)
#define PixelHeight_ID (0xba)
#define PixelHeight_TYPE (uint64_t)
#define PixelCropBottom_ID (0x54aa)
#define PixelCropBottom_TYPE (uint64_t)
#define PixelCropTop_ID (0x54bb)
#define PixelCropTop_TYPE (uint64_t)
#define PixelCropLeft_ID (0x54cc)
#define PixelCropLeft_TYPE (uint64_t)
#define PixelCropRight_ID (0x54dd)
#define PixelCropRight_TYPE (uint64_t)
#define DisplayWidth_ID (0x54b0)
#define DisplayWidth_TYPE (uint64_t)
#define DisplayHeight_ID (0x54ba)
#define DisplayHeight_TYPE (uint64_t)
#define DisplayUnit_ID (0x54b2)
#define DisplayUnit_TYPE (uint64_t)
#define AspectRatioType_ID (0x54b3)
#define AspectRatioType_TYPE (uint64_t)
#define UncompressedFourCC_ID (0x2eb524)
#define UncompressedFourCC_TYPE (Binary)
#define GammaValue_ID (0x2fb523)
#define GammaValue_TYPE (float_t)
#define FrameRate_ID (0x2383e3)
#define FrameRate_TYPE (float_t)
#define Colour_ID (0x55b0)
#define Colour_TYPE (Master)
#define MatrixCoefficients_ID (0x55b1)
#define MatrixCoefficients_TYPE (uint64_t)
#define BitsPerChannel_ID (0x55b2)
#define BitsPerChannel_TYPE (uint64_t)
#define ChromaSubsamplingHorz_ID (0x55b3)
#define ChromaSubsamplingHorz_TYPE (uint64_t)
#define ChromaSubsamplingVert_ID (0x55b4)
#define ChromaSubsamplingVert_TYPE (uint64_t)
#define CbSubsamplingHorz_ID (0x55b5)
#define CbSubsamplingHorz_TYPE (uint64_t)
#define CbSubsamplingVert_ID (0x55b6)
#define CbSubsamplingVert_TYPE (uint64_t)
#define ChromaSitingHorz_ID (0x55b7)
#define ChromaSitingHorz_TYPE (uint64_t)
#define ChromaSitingVert_ID (0x55b8)
#define ChromaSitingVert_TYPE (uint64_t)
#define Range_ID (0x55b9)
#define Range_TYPE (uint64_t)
#define TransferCharacteristics_ID (0x55ba)
#define TransferCharacteristics_TYPE (uint64_t)
#define Primaries_ID (0x55bb)
#define Primaries_TYPE (uint64_t)
#define MaxCLL_ID (0x55bc)
#define MaxCLL_TYPE (uint64_t)
#define MaxFALL_ID (0x55bd)
#define MaxFALL_TYPE (uint64_t)
#define MasteringMetadata_ID (0x55d0)
#define MasteringMetadata_TYPE (Master)
#define PrimaryRChromaticityX_ID (0x55d1)
#define PrimaryRChromaticityX_TYPE (float_t)
#define PrimaryRChromaticityY_ID (0x55d2)
#define PrimaryRChromaticityY_TYPE (float_t)
#define PrimaryGChromaticityX_ID (0x55d3)
#define PrimaryGChromaticityX_TYPE (float_t)
#define PrimaryGChromaticityY_ID (0x55d4)
#define PrimaryGChromaticityY_TYPE (float_t)
#define PrimaryBChromaticityX_ID (0x55d5)
#define PrimaryBChromaticityX_TYPE (float_t)
#define PrimaryBChromaticityY_ID (0x55d6)
#define PrimaryBChromaticityY_TYPE (float_t)
#define WhitePointChromaticityX_ID (0x55d7)
#define WhitePointChromaticityX_TYPE (float_t)
#define WhitePointChromaticityY_ID (0x55d8)
#define WhitePointChromaticityY_TYPE (float_t)
#define LuminanceMax_ID (0x55d9)
#define LuminanceMax_TYPE (float_t)
#define LuminanceMin_ID (0x55da)
#define LuminanceMin_TYPE (float_t)
#define Projection_ID (0x7670)
#define Projection_TYPE (Master)
#define ProjectionType_ID (0x7671)
#define ProjectionType_TYPE (uint64_t)
#define ProjectionPrivate_ID (0x7672)
#define ProjectionPrivate_TYPE (Binary)
#define ProjectionPoseYaw_ID (0x7673)
#define ProjectionPoseYaw_TYPE (float_t)
#define ProjectionPosePitch_ID (0x7674)
#define ProjectionPosePitch_TYPE (float_t)
#define ProjectionPoseRoll_ID (0x7675)
#define ProjectionPoseRoll_TYPE (float_t)
#define Audio_ID (0xe1)
#define Audio_TYPE (Master)
#define SamplingFrequency_ID (0xb5)
#define SamplingFrequency_TYPE (float_t)
#define OutputSamplingFrequency_ID (0x78b5)
#define OutputSamplingFrequency_TYPE (float_t)
#define Channels_ID (0x9f)
#define Channels_TYPE (uint64_t)
#define ChannelPositions_ID (0x7d7b)
#define ChannelPositions_TYPE (Binary)
#define BitDepth_ID (0x6264)
#define BitDepth_TYPE (uint64_t)
#define TrackOperation_ID (0xe2)
#define TrackOperation_TYPE (Master)
#define TrackCombinePlanes_ID (0xe3)
#define TrackCombinePlanes_TYPE (Master)
#define TrackPlane_ID (0xe4)
#define TrackPlane_TYPE (Master)
#define TrackPlaneUID_ID (0xe5)
#define TrackPlaneUID_TYPE (uint64_t)
#define TrackPlaneType_ID (0xe6)
#define TrackPlaneType_TYPE (uint64_t)
#define TrackJoinBlocks_ID (0xe9)
#define TrackJoinBlocks_TYPE (Master)
#define TrackJoinUID_ID (0xed)
#define TrackJoinUID_TYPE (uint64_t)
#define TrickTrackUID_ID (0xc0)
#define TrickTrackUID_TYPE (uint64_t)
#define TrickTrackSegmentUID_ID (0xc1)
#define TrickTrackSegmentUID_TYPE (Binary)
#define TrickTrackFlag_ID (0xc6)
#define TrickTrackFlag_TYPE (uint64_t)
#define TrickMasterTrackUID_ID (0xc7)
#define TrickMasterTrackUID_TYPE (uint64_t)
#define TrickMasterTrackSegmentUID_ID (0xc4)
#define TrickMasterTrackSegmentUID_TYPE (Binary)
#define ContentEncodings_ID (0x6d80)
#define ContentEncodings_TYPE (Master)
#define ContentEncoding_ID (0x6240)
#define ContentEncoding_TYPE (Master)
#define ContentEncodingOrder_ID (0x5031)
#define ContentEncodingOrder_TYPE (uint64_t)
#define ContentEncodingScope_ID (0x5032)
#define ContentEncodingScope_TYPE (uint64_t)
#define ContentEncodingType_ID (0x5033)
#define ContentEncodingType_TYPE (uint64_t)
#define ContentCompression_ID (0x5034)
#define ContentCompression_TYPE (Master)
#define ContentCompAlgo_ID (0x4254)
#define ContentCompAlgo_TYPE (uint64_t)
#define ContentCompSettings_ID (0x4255)
#define ContentCompSettings_TYPE (Binary)
#define ContentEncryption_ID (0x5035)
#define ContentEncryption_TYPE (Master)
#define ContentEncAlgo_ID (0x47e1)
#define ContentEncAlgo_TYPE (uint64_t)
#define ContentEncKeyID_ID (0x47e2)
#define ContentEncKeyID_TYPE (Binary)
#define ContentEncAESSettings_ID (0x47e7)
#define ContentEncAESSettings_TYPE (Master)
#define AESSettingsCipherMode_ID (0x47e8)
#define AESSettingsCipherMode_TYPE (uint64_t)
#define ContentSignature_ID (0x47e3)
#define ContentSignature_TYPE (Binary)
#define ContentSigKeyID_ID (0x47e4)
#define ContentSigKeyID_TYPE (Binary)
#define ContentSigAlgo_ID (0x47e5)
#define ContentSigAlgo_TYPE (uint64_t)
#define ContentSigHashAlgo_ID (0x47e6)
#define ContentSigHashAlgo_TYPE (uint64_t)
#define Cues_ID (0x1c53bb6b)
#define Cues_TYPE (Master)
#define CuePoint_ID (0xbb)
#define CuePoint_TYPE (Master)
#define CueTime_ID (0xb3)
#define CueTime_TYPE (uint64_t)
#define CueTrackPositions_ID (0xb7)
#define CueTrackPositions_TYPE (Master)
#define CueTrack_ID (0xf7)
#define CueTrack_TYPE (uint64_t)
#define CueClusterPosition_ID (0xf1)
#define CueClusterPosition_TYPE (uint64_t)
#define CueRelativePosition_ID (0xf0)
#define CueRelativePosition_TYPE (uint64_t)
#define CueDuration_ID (0xb2)
#define CueDuration_TYPE (uint64_t)
#define CueBlockNumber_ID (0x5378)
#define CueBlockNumber_TYPE (uint64_t)
#define CueCodecState_ID (0xea)
#define CueCodecState_TYPE (uint64_t)
#define CueReference_ID (0xdb)
#define CueReference_TYPE (Master)
#define CueRefTime_ID (0x96)
#define CueRefTime_TYPE (uint64_t)
#define CueRefCluster_ID (0x97)
#define CueRefCluster_TYPE (uint64_t)
#define CueRefNumber_ID (0x535f)
#define CueRefNumber_TYPE (uint64_t)
#define CueRefCodecState_ID (0xeb)
#define CueRefCodecState_TYPE (uint64_t)
#define Attachments_ID (0x1941a469)
#define Attachments_TYPE (Master)
#define AttachedFile_ID (0x61a7)
#define AttachedFile_TYPE (Master)
#define FileDescription_ID (0x467e)
#define FileDescription_TYPE (string)
#define FileName_ID (0x466e)
#define FileName_TYPE (string)
#define FileMimeType_ID (0x4660)
#define FileMimeType_TYPE (string)
#define FileData_ID (0x465c)
#define FileData_TYPE (Binary)
#define FileUID_ID (0x46ae)
#define FileUID_TYPE (uint64_t)
#define FileReferral_ID (0x4675)
#define FileReferral_TYPE (Binary)
#define FileUsedStartTime_ID (0x4661)
#define FileUsedStartTime_TYPE (uint64_t)
#define FileUsedEndTime_ID (0x4662)
#define FileUsedEndTime_TYPE (uint64_t)
#define Chapters_ID (0x1043a770)
#define Chapters_TYPE (Master)
#define EditionEntry_ID (0x45b9)
#define EditionEntry_TYPE (Master)
#define EditionUID_ID (0x45bc)
#define EditionUID_TYPE (uint64_t)
#define EditionFlagHidden_ID (0x45bd)
#define EditionFlagHidden_TYPE (uint64_t)
#define EditionFlagDefault_ID (0x45db)
#define EditionFlagDefault_TYPE (uint64_t)
#define EditionFlagOrdered_ID (0x45dd)
#define EditionFlagOrdered_TYPE (uint64_t)
#define ChapterAtom_ID (0xb6)
#define ChapterAtom_TYPE (Master)
#define ChapterUID_ID (0x73c4)
#define ChapterUID_TYPE (uint64_t)
#define ChapterStringUID_ID (0x5654)
#define ChapterStringUID_TYPE (string)
#define ChapterTimeStart_ID (0x91)
#define ChapterTimeStart_TYPE (uint64_t)
#define ChapterTimeEnd_ID (0x92)
#define ChapterTimeEnd_TYPE (uint64_t)
#define ChapterFlagHidden_ID (0x98)
#define ChapterFlagHidden_TYPE (uint64_t)
#define ChapterFlagEnabled_ID (0x4598)
#define ChapterFlagEnabled_TYPE (uint64_t)
#define ChapterSegmentUID_ID (0x6e67)
#define ChapterSegmentUID_TYPE (Binary)
#define ChapterSegmentEditionUID_ID (0x6ebc)
#define ChapterSegmentEditionUID_TYPE (uint64_t)
#define ChapterPhysicalEquiv_ID (0x63c3)
#define ChapterPhysicalEquiv_TYPE (uint64_t)
#define ChapterTrack_ID (0x8f)
#define ChapterTrack_TYPE (Master)
#define ChapterTrackUID_ID (0x89)
#define ChapterTrackUID_TYPE (uint64_t)
#define ChapterDisplay_ID (0x80)
#define ChapterDisplay_TYPE (Master)
#define ChapString_ID (0x85)
#define ChapString_TYPE (string)
#define ChapLanguage_ID (0x437c)
#define ChapLanguage_TYPE (string)
#define ChapLanguageIETF_ID (0x437d)
#define ChapLanguageIETF_TYPE (string)
#define ChapCountry_ID (0x437e)
#define ChapCountry_TYPE (string)
#define ChapProcess_ID (0x6944)
#define ChapProcess_TYPE (Master)
#define ChapProcessCodecID_ID (0x6955)
#define ChapProcessCodecID_TYPE (uint64_t)
#define ChapProcessPrivate_ID (0x450d)
#define ChapProcessPrivate_TYPE (Binary)
#define ChapProcessCommand_ID (0x6911)
#define ChapProcessCommand_TYPE (Master)
#define ChapProcessTime_ID (0x6922)
#define ChapProcessTime_TYPE (uint64_t)
#define ChapProcessData_ID (0x6933)
#define ChapProcessData_TYPE (Binary)
#define Tags_ID (0x1254c367)
#define Tags_TYPE (Master)
#define Tag_ID (0x7373)
#define Tag_TYPE (Master)
#define Targets_ID (0x63c0)
#define Targets_TYPE (Master)
#define TargetTypeValue_ID (0x68ca)
#define TargetTypeValue_TYPE (uint64_t)
#define TargetType_ID (0x63ca)
#define TargetType_TYPE (string)
#define TagTrackUID_ID (0x63c5)
#define TagTrackUID_TYPE (uint64_t)
#define TagEditionUID_ID (0x63c9)
#define TagEditionUID_TYPE (uint64_t)
#define TagChapterUID_ID (0x63c4)
#define TagChapterUID_TYPE (uint64_t)
#define TagAttachmentUID_ID (0x63c6)
#define TagAttachmentUID_TYPE (uint64_t)
#define SimpleTag_ID (0x67c8)
#define SimpleTag_TYPE (Master)
#define TagName_ID (0x45a3)
#define TagName_TYPE (string)
#define TagLanguage_ID (0x447a)
#define TagLanguage_TYPE (string)
#define TagLanguageIETF_ID (0x447b)
#define TagLanguageIETF_TYPE (string)
#define TagDefault_ID (0x4484)
#define TagDefault_TYPE (uint64_t)
#define TagDefaultBogus_ID (0x44b4)
#define TagDefaultBogus_TYPE (uint64_t)
#define TagString_ID (0x4487)
#define TagString_TYPE (string)
#define TagBinary_ID (0x4485)
#define TagBinary_TYPE (Binary

namespace Matroska
{
    enum class ChapterTranslateCodecValues {
        MatroskaScript = 0,
        DvdMenu = 1
    };
    enum class TrackTypeValues {
        Video = 1,
        Audio = 2,
        Complex = 3,
        Logo = 16,
        Subtitle = 17,
        Buttons = 18,
        Control = 32,
        Metadata = 33
    };
    enum class TrackTranslateCodecValues {
        MatroskaScript = 0,
        DvdMenu = 1
    };
    enum class FlagInterlacedValues {
        Undetermined = 0,
        Interlaced = 1,
        Progressive = 2
    };
    enum class FieldOrderValues {
        Progressive = 0,
        Tff = 1,
        Undetermined = 2,
        Bff = 6,
        BffSwapped = 9,
        TffSwapped = 14
    };
    enum class StereoModeValues {
        Mono = 0,
        SideBySideLeftEyeFirst = 1,
        TopToBottomRightEyeIsFirst = 2,
        TopToBottomLeftEyeIsFirst = 3,
        CheckboardRightEyeIsFirst = 4,
        CheckboardLeftEyeIsFirst = 5,
        RowInterleavedRightEyeIsFirst = 6,
        RowInterleavedLeftEyeIsFirst = 7,
        ColumnInterleavedRightEyeIsFirst = 8,
        ColumnInterleavedLeftEyeIsFirst = 9,
        AnaglyphCyanOrRed = 10,
        SideBySideRightEyeFirst = 11,
        AnaglyphGreenOrMagenta = 12,
        BothEyesLacedInOneBlockLeftEyeIsFirst = 13,
        BothEyesLacedInOneBlockRightEyeIsFirst = 14
    };
    enum class OldStereoModeValues {
        Mono = 0,
        RightEye = 1,
        LeftEye = 2,
        BothEyes = 3
    };
    enum class DisplayUnitValues {
        Pixels = 0,
        Centimeters = 1,
        Inches = 2,
        DisplayAspectRatio = 3,
        Unknown = 4
    };
    enum class AspectRatioTypeValues {
        FreeResizing = 0,
        KeepAspectRatio = 1,
        Fixed = 2
    };
    enum class MatrixCoefficientsValues {
        Identity = 0,
        ItuRBt_709 = 1,
        Unspecified = 2,
        Reserved = 3,
        UsFcc73_682 = 4,
        ItuRBt_470bg = 5,
        Smpte170m = 6,
        Smpte240m = 7,
        Ycocg = 8,
        Bt2020NonConstantLuminance = 9,
        Bt2020ConstantLuminance = 10,
        SmpteSt2085 = 11,
        ChromaDerivedNonConstantLuminance = 12,
        ChromaDerivedConstantLuminance = 13,
        ItuRBt_21000 = 14
    };
    enum class ChromaSitingHorzValues {
        Unspecified = 0,
        LeftCollocated = 1,
        Half = 2
    };
    enum class ChromaSitingVertValues {
        Unspecified = 0,
        TopCollocated = 1,
        Half = 2
    };
    enum class RangeValues {
        Unspecified = 0,
        BroadcastRange = 1,
        FullRangeNoClipping = 2,
        DefinedByMatrixcoefficientsOrTransfercharacteristics = 3
    };
    enum class TransferCharacteristicsValues {
        Reserved = 0,
        ItuRBt_709 = 1,
        Unspecified = 2,
        Reserved2 = 3,
        Gamma2_2CurveToBt_470m = 4,
        Gamma2_8CurveToBt_470bg = 5,
        Smpte170m = 6,
        Smpte240m = 7,
        Linear = 8,
        Log = 9,
        LogSqrt = 10,
        Iec6196624 = 11,
        ItuRBt_1361ExtendedColourGamut = 12,
        Iec6196621 = 13,
        ItuRBt_202010Bit = 14,
        ItuRBt_202012Bit = 15,
        ItuRBt_2100PerceptualQuantization = 16,
        SmpteSt4281 = 17,
        AribStdB67Hlg = 18
    };
    enum class PrimariesValues {
        Reserved = 0,
        ItuRBt_709 = 1,
        Unspecified = 2,
        Reserved2 = 3,
        ItuRBt_470m = 4,
        ItuRBt_470bgToBt_601625 = 5,
        ItuRBt_601525ToSmpte170m = 6,
        Smpte240m = 7,
        Film = 8,
        ItuRBt_2020 = 9,
        SmpteSt4281 = 10,
        SmpteRp4322 = 11,
        SmpteEg4322 = 12,
        EbuTech_3213EToJedecP22Phosphors = 22
    };
    enum class ProjectionTypeValues {
        Rectangular = 0,
        Equirectangular = 1,
        Cubemap = 2,
        Mesh = 3
    };
    enum class TrackPlaneTypeValues {
        LeftEye = 0,
        RightEye = 1,
        Background = 2
    };
    enum class ContentEncodingScopeValues {
        AllFrameContentsExcludingLacingData = 1,
        TheTracksPrivateData = 2,
        TheNextContentencodingNextContentencodingorder_EitherTheDataInsideContentcompressionAndOrOrContentencryption = 4
    };
    enum class ContentEncodingTypeValues {
        Compression = 0,
        Encryption = 1
    };
    enum class ContentCompAlgoValues {
        Zlib = 0,
        Bzlib = 1,
        Lzo1x = 2,
        HeaderStripping = 3
    };
    enum class ContentEncAlgoValues {
        NotEncrypted = 0,
        Des = 1,
        ThreeDes = 2,
        Twofish = 3,
        Blowfish = 4,
        Aes = 5
    };
    enum class AESSettingsCipherModeValues {
        AesCtrOrCounterNistSp80038a = 1,
        AesCbcOrCipherBlockChainingNistSp80038a = 2
    };
    enum class ContentSigAlgoValues {
        NotSigned = 0,
        Rsa = 1
    };
    enum class ContentSigHashAlgoValues {
        NotSigned = 0,
        Sha1160 = 1,
        Md5 = 2
    };
    enum class ChapProcessTimeValues {
        DuringTheWholeChapter = 0,
        BeforeStartingPlayback = 1,
        AfterPlaybackOfTheChapter = 2
    };
    enum class TargetTypeValueValues {
        Collection = 70,
        EditionOrIssueOrVolumeOrOpusOrSeasonOrSequel = 60,
        AlbumOrOperaOrConcertOrMovieOrEpisodeOrConcert = 50,
        PartOrSession = 40,
        TrackOrSongOrChapter = 30,
        SubtrackOrPartOrMovementOrScene = 20,
        Shot = 10
    };
/*    enum class TargetTypeValues {
        Collection = 'COLLECTION',
        Edition = 'EDITION',
        Issue = 'ISSUE',
        Volume = 'VOLUME',
        Opus = 'OPUS',
        Season = 'SEASON',
        Sequel = 'SEQUEL',
        Album = 'ALBUM',
        Opera = 'OPERA',
        Concert = 'CONCERT',
        Movie = 'MOVIE',
        Episode = 'EPISODE',
        Part = 'PART',
        Session = 'SESSION',
        Track = 'TRACK',
        Song = 'SONG',
        Chapter = 'CHAPTER',
        Subtrack = 'SUBTRACK',
        Movement = 'MOVEMENT',
        Scene = 'SCENE',
        Shot = 'SHOT'
    };*/
}