/*   
 *   Matroska track setter  Copyright (C) 2021  Kyoya2
 *   
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *   
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *   
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#pragma once

#include <array>
#include <algorithm>

#include "Common.h"

struct LanguageDescriptor
{
    vector<string_view> language_names;
    vector<string_view> tags;
};

namespace MatroskaLanguageTags
{
    static const string_view UNKNOWN_LANGUGAGE = "UNKNOWN";
    static const std::array<LanguageDescriptor, 487> language_tags{{
        {{"Abkhazian"}, {"abk", "ab"}},
        {{"Achinese"}, {"ace"}},
        {{"Acoli"}, {"ach"}},
        {{"Adangme"}, {"ada"}},
        {{"Adyghe", "Adygei"}, {"ady"}},
        {{"Afar"}, {"aar", "aa"}},
        {{"Afrihili"}, {"afh"}},
        {{"Afrikaans"}, {"afr", "af"}},
        {{"Afro-Asiatic languages"}, {"afa"}},
        {{"Ainu"}, {"ain"}},
        {{"Akan"}, {"ak", "aka"}},
        {{"Akkadian"}, {"akk"}},
        {{"Albanian"}, {"sq", "sqi", "alb"}},
        {{"Alemannic", "Swiss German", "Alsatian"}, {"gsw"}},
        {{"Aleut"}, {"ale"}},
        {{"Algonquian languages"}, {"alg"}},
        {{"Altaic languages"}, {"tut"}},
        {{"Amharic"}, {"am", "amh"}},
        {{"Angika"}, {"anp"}},
        {{"Apache languages"}, {"apa"}},
        {{"Arabic"}, {"ara", "ar"}},
        {{"Aragonese"}, {"arg", "an"}},
        {{"Arapaho"}, {"arp"}},
        {{"Arawak"}, {"arw"}},
        {{"Armenian"}, {"arm", "hye", "hy"}},
        {{"Aromanian", "Macedo-Romanian", "Arumanian"}, {"rup"}},
        {{"Artificial languages"}, {"art"}},
        {{"Assamese"}, {"asm", "as"}},
        {{"Asturleonese", "Bable", "Leonese", "Asturian"}, {"ast"}},
        {{"Athapascan languages"}, {"ath"}},
        {{"Australian languages"}, {"aus"}},
        {{"Austronesian languages"}, {"map"}},
        {{"Avaric"}, {"ava", "av"}},
        {{"Avestan"}, {"ave", "ae"}},
        {{"Awadhi"}, {"awa"}},
        {{"Aymara"}, {"aym", "ay"}},
        {{"Azerbaijani"}, {"az", "aze"}},
        {{"Balinese"}, {"ban"}},
        {{"Baltic languages"}, {"bat"}},
        {{"Baluchi"}, {"bal"}},
        {{"Bambara"}, {"bam", "bm"}},
        {{"Bamileke languages"}, {"bai"}},
        {{"Banda languages"}, {"bad"}},
        {{"Bantu languages"}, {"bnt"}},
        {{"Basa"}, {"bas"}},
        {{"Bashkir"}, {"bak", "ba"}},
        {{"Basque"}, {"baq", "eus", "eu"}},
        {{"Batak languages"}, {"btk"}},
        {{"Bedawiyet", "Beja"}, {"bej"}},
        {{"Belarusian"}, {"be", "bel"}},
        {{"Bemba"}, {"bem"}},
        {{"Bengali"}, {"ben"}},
        {{"Berber languages"}, {"ber"}},
        {{"Bhojpuri"}, {"bho"}},
        {{"Bihari languages"}, {"bh", "bih"}},
        {{"Bikol"}, {"bik"}},
        {{"Bilin", "Blin"}, {"byn"}},
        {{"Bislama"}, {"bi", "bis"}},
        {{"Blissymbols", "Bliss", "Blissymbolics"}, {"zbl"}},
        {{"Bosnian"}, {"bos", "bs"}},
        {{"Braj"}, {"bra"}},
        {{"Breton"}, {"br", "bre"}},
        {{"Buginese"}, {"bug"}},
        {{"Bulgarian"}, {"bg", "bul"}},
        {{"Buriat"}, {"bua"}},
        {{"Burmese"}, {"my", "mya", "bur"}},
        {{"Caddo"}, {"cad"}},
        {{"Catalan", "Valencian"}, {"ca", "cat"}},
        {{"Caucasian languages"}, {"cau"}},
        {{"Cebuano"}, {"ceb"}},
        {{"Celtic languages"}, {"cel"}},
        {{"Central American Indian languages"}, {"cai"}},
        {{"Central Khmer"}, {"khm", "km"}},
        {{"Chagatai"}, {"chg"}},
        {{"Chamic languages"}, {"cmc"}},
        {{"Chamorro"}, {"cha", "ch"}},
        {{"Chechen"}, {"ce", "che"}},
        {{"Cherokee"}, {"chr"}},
        {{"Chewa", "Chichewa", "Nyanja"}, {"nya", "ny"}},
        {{"Cheyenne"}, {"chy"}},
        {{"Chibcha"}, {"chb"}},
        {{"Chinese"}, {"chi", "zho", "zh"}},
        {{"Chinook jargon"}, {"chn"}},
        {{"Choctaw"}, {"cho"}},
        {{"Chuukese"}, {"chk"}},
        {{"Chuvash"}, {"chv", "cv"}},
        {{"Classical Nepal Bhasa", "Old Newari", "Classical Newari"}, {"nwc"}},
        {{"Classical Syriac"}, {"syc"}},
        {{"Cook Islands Maori", "Rarotongan"}, {"rar"}},
        {{"Coptic"}, {"cop"}},
        {{"Cornish"}, {"cor", "kw"}},
        {{"Corsican"}, {"cos", "co"}},
        {{"Cree"}, {"cre", "cr"}},
        {{"Creek"}, {"mus"}},
        {{"Creoles and pidgins"}, {"crp"}},
        {{"Creoles and pidgins, English based"}, {"cpe"}},
        {{"Creoles and pidgins, French-based"}, {"cpf"}},
        {{"Creoles and pidgins, Portuguese-based"}, {"cpp"}},
        {{"Crimean Turkish", "Crimean Tatar"}, {"crh"}},
        {{"Croatian"}, {"hr", "hrv"}},
        {{"Cushitic languages"}, {"cus"}},
        {{"Czech"}, {"cze", "cs", "ces"}},
        {{"Dakota"}, {"dak"}},
        {{"Danish"}, {"dan", "da"}},
        {{"Dargwa"}, {"dar"}},
        {{"Delaware"}, {"del"}},
        {{"Dene Suline", "Chipewyan"}, {"chp"}},
        {{"Dhivehi", "Maldivian", "Divehi"}, {"dv", "div"}},
        {{"Dimli", "Zazaki", "Kirdki", "Zaza", "Kirmanjki", "Dimili"}, {"zza"}},
        {{"Dinka"}, {"din"}},
        {{"Dogri"}, {"doi"}},
        {{"Dogrib"}, {"dgr"}},
        {{"Dravidian languages"}, {"dra"}},
        {{"Duala"}, {"dua"}},
        {{"Dutch, Middle (ca.1050-1350)"}, {"dum"}},
        {{"Dyula"}, {"dyu"}},
        {{"Dzongkha"}, {"dzo", "dz"}},
        {{"Eastern Frisian"}, {"frs"}},
        {{"Edo", "Bini"}, {"bin"}},
        {{"Efik"}, {"efi"}},
        {{"Egyptian (Ancient)"}, {"egy"}},
        {{"Ekajuk"}, {"eka"}},
        {{"Elamite"}, {"elx"}},
        {{"English"}, {"eng", "en"}},
        {{"English, Middle (1100-1500)"}, {"enm"}},
        {{"English, Old (ca.450-1100)"}, {"ang"}},
        {{"Erzya"}, {"myv"}},
        {{"Esperanto"}, {"epo", "eo"}},
        {{"Estonian"}, {"est", "et"}},
        {{"Ewe"}, {"ewe", "ee"}},
        {{"Ewondo"}, {"ewo"}},
        {{"Fang"}, {"fan"}},
        {{"Fanti"}, {"fat"}},
        {{"Faroese"}, {"fo", "fao"}},
        {{"Fijian"}, {"fj", "fij"}},
        {{"Finnish"}, {"fin", "fi"}},
        {{"Finno-Ugrian languages"}, {"fiu"}},
        {{"Flemish", "Dutch"}, {"nld", "dut", "nl"}},
        {{"Fon"}, {"fon"}},
        {{"French"}, {"fra", "fre", "fr"}},
        {{"French, Middle (ca.1400-1600)"}, {"frm"}},
        {{"French, Old (842-ca.1400)"}, {"fro"}},
        {{"Friulian"}, {"fur"}},
        {{"Fulah"}, {"ff", "ful"}},
        {{"Ga"}, {"gaa"}},
        {{"Galibi Carib"}, {"car"}},
        {{"Galician"}, {"glg", "gl"}},
        {{"Ganda"}, {"lug"}},
        {{"Gayo"}, {"gay"}},
        {{"Gbaya"}, {"gba"}},
        {{"Geez"}, {"gez"}},
        {{"Georgian"}, {"geo", "ka", "kat"}},
        {{"German"}, {"deu", "de", "ger"}},
        {{"German, Middle High (ca.1050-1500)"}, {"gmh"}},
        {{"German, Old High (ca.750-1050)"}, {"goh"}},
        {{"Germanic languages"}, {"gem"}},
        {{"Gikuyu", "Kikuyu"}, {"ki", "kik"}},
        {{"Gilbertese"}, {"gil"}},
        {{"Gondi"}, {"gon"}},
        {{"Gorontalo"}, {"gor"}},
        {{"Gothic"}, {"got"}},
        {{"Grebo"}, {"grb"}},
        {{"Greek, Ancient (to 1453)"}, {"grc"}},
        {{"Greek, Modern (1453-)"}, {"gre", "ell"}},
        {{"Guarani"}, {"grn", "gn"}},
        {{"Gujarati"}, {"guj", "gu"}},
        {{"Gwich'in"}, {"gwi"}},
        {{"Haida"}, {"hai"}},
        {{"Haitian", "Haitian Creole"}, {"hat", "ht"}},
        {{"Hausa"}, {"ha", "hau"}},
        {{"Hawaiian"}, {"haw"}},
        {{"Hebrew"}, {"heb", "he"}},
        {{"Herero"}, {"hz", "her"}},
        {{"Hiligaynon"}, {"hil"}},
        {{"Hindi"}, {"hi", "hin"}},
        {{"Hiri Motu"}, {"ho", "hmo"}},
        {{"Hittite"}, {"hit"}},
        {{"Hungarian"}, {"hun", "hu"}},
        {{"Hupa"}, {"hup"}},
        {{"Iban"}, {"iba"}},
        {{"Icelandic"}, {"is", "isl", "ice"}},
        {{"Ido"}, {"ido", "io"}},
        {{"Igbo"}, {"ig", "ibo"}},
        {{"Ijo languages"}, {"ijo"}},
        {{"Iloko"}, {"ilo"}},
        {{"Inari Sami"}, {"smn"}},
        {{"Indic languages"}, {"inc"}},
        {{"Indo-European languages"}, {"ine"}},
        {{"Indonesian"}, {"ind", "id"}},
        {{"Ingush"}, {"inh"}},
        {{"Interlingua (International Auxiliary Language Association)"}, {"ina", "ia"}},
        {{"Interlingue", "Occidental"}, {"ie", "ile"}},
        {{"Inuktitut"}, {"iu", "iku"}},
        {{"Inupiaq"}, {"ipk", "ik"}},
        {{"Iranian languages"}, {"ira"}},
        {{"Irish"}, {"gle", "ga"}},
        {{"Irish, Middle (900-1200)"}, {"mga"}},
        {{"Irish, Old (to 900)"}, {"sga"}},
        {{"Iroquoian languages"}, {"iro"}},
        {{"Italian"}, {"it", "ita"}},
        {{"Japanese"}, {"ja", "jpn"}},
        {{"Javanese"}, {"jv", "jav"}},
        {{"Judeo-Arabic"}, {"jrb"}},
        {{"Judeo-Persian"}, {"jpr"}},
        {{"Kabardian"}, {"kbd"}},
        {{"Kabyle"}, {"kab"}},
        {{"Kachin", "Jingpho"}, {"kac"}},
        {{"Kalaallisut", "Greenlandic"}, {"kl", "kal"}},
        {{"Kalmyk", "Oirat"}, {"xal"}},
        {{"Kamba"}, {"kam"}},
        {{"Kannada"}, {"kan", "kn"}},
        {{"Kanuri"}, {"kau", "kr"}},
        {{"Kara-Kalpak"}, {"kaa"}},
        {{"Karachay-Balkar"}, {"krc"}},
        {{"Karelian"}, {"krl"}},
        {{"Karen languages"}, {"kar"}},
        {{"Kashmiri"}, {"kas", "ks"}},
        {{"Kashubian"}, {"csb"}},
        {{"Kawi"}, {"kaw"}},
        {{"Kazakh"}, {"kk", "kaz"}},
        {{"Khasi"}, {"kha"}},
        {{"Khoisan languages"}, {"khi"}},
        {{"Khotanese", "Sakan"}, {"kho"}},
        {{"Kimbundu"}, {"kmb"}},
        {{"Kinyarwanda"}, {"kin", "rw"}},
        {{"Klingon", "tlhIngan-Hol"}, {"tlh"}},
        {{"Komi"}, {"kom", "kv"}},
        {{"Kongo"}, {"kon", "kg"}},
        {{"Konkani"}, {"kok"}},
        {{"Korean"}, {"kor", "ko"}},
        {{"Kosraean"}, {"kos"}},
        {{"Kpelle"}, {"kpe"}},
        {{"Kru languages"}, {"kro"}},
        {{"Kuanyama", "Kwanyama"}, {"kj", "kua"}},
        {{"Kumyk"}, {"kum"}},
        {{"Kurdish"}, {"kur", "ku"}},
        {{"Kurukh"}, {"kru"}},
        {{"Kutenai"}, {"kut"}},
        {{"Kyrgyz", "Kirghiz"}, {"ky", "kir"}},
        {{"Ladino"}, {"lad"}},
        {{"Lahnda"}, {"lah"}},
        {{"Lamba"}, {"lam"}},
        {{"Land Dayak languages"}, {"day"}},
        {{"Lao"}, {"lao", "lo"}},
        {{"Latin"}, {"la", "lat"}},
        {{"Latvian"}, {"lav", "lv"}},
        {{"Lezghian"}, {"lez"}},
        {{"Limburger", "Limburgish", "Limburgan"}, {"lim", "li"}},
        {{"Lingala"}, {"lin", "ln"}},
        {{"Lithuanian"}, {"lt", "lit"}},
        {{"Lojban"}, {"jbo"}},
        {{"Low German", "German, Low", "Low Saxon", "Saxon, Low"}, {"nds"}},
        {{"Lower Sorbian"}, {"dsb"}},
        {{"Lozi"}, {"loz"}},
        {{"Luba-Katanga"}, {"lub", "lu"}},
        {{"Luba-Lulua"}, {"lua"}},
        {{"Luiseno"}, {"lui"}},
        {{"Lule Sami"}, {"smj"}},
        {{"Lunda"}, {"lun"}},
        {{"Luo (Kenya and Tanzania)"}, {"luo"}},
        {{"Lushai"}, {"lus"}},
        {{"Luxembourgish", "Letzeburgesch"}, {"lb", "ltz"}},
        {{"Macedonian"}, {"mkd", "mk", "mac"}},
        {{"Madurese"}, {"mad"}},
        {{"Magahi"}, {"mag"}},
        {{"Maithili"}, {"mai"}},
        {{"Makasar"}, {"mak"}},
        {{"Malagasy"}, {"mg", "mlg"}},
        {{"Malay"}, {"may", "msa"}},
        {{"Malayalam"}, {"ml", "mal"}},
        {{"Maltese"}, {"mt", "mlt"}},
        {{"Manchu"}, {"mnc"}},
        {{"Mandar"}, {"mdr"}},
        {{"Mandingo"}, {"man"}},
        {{"Manipuri"}, {"mni"}},
        {{"Manobo languages"}, {"mno"}},
        {{"Manx"}, {"gv", "glv"}},
        {{"Maori"}, {"mao", "mri", "mi"}},
        {{"Mapudungun", "Mapuche"}, {"arn"}},
        {{"Marathi"}, {"mar", "mr"}},
        {{"Mari"}, {"chm"}},
        {{"Marshallese"}, {"mah", "mh"}},
        {{"Marwari"}, {"mwr"}},
        {{"Masai"}, {"mas"}},
        {{"Mayan languages"}, {"myn"}},
        {{"Mende"}, {"men"}},
        {{"Mi'kmaq", "Micmac"}, {"mic"}},
        {{"Minangkabau"}, {"min"}},
        {{"Mirandese"}, {"mwl"}},
        {{"Mohawk"}, {"moh"}},
        {{"Moksha"}, {"mdf"}},
        {{"Moldovan", "Moldavian", "Romanian"}, {"ron", "rum", "mo"}},
        {{"Mon-Khmer languages"}, {"mkh"}},
        {{"Mong", "Hmong"}, {"hmn"}},
        {{"Mongo"}, {"lol"}},
        {{"Mongolian"}, {"mn", "mon"}},
        {{"Montenegrin"}, {"cnr"}},
        {{"Mossi"}, {"mos"}},
        {{"Multiple languages"}, {"mul"}},
        {{"Munda languages"}, {"mun"}},
        {{"N'Ko"}, {"nqo"}},
        {{"Nahuatl languages"}, {"nah"}},
        {{"Nauru"}, {"na", "nau"}},
        {{"Navaho", "Navajo"}, {"nv", "nav"}},
        {{"Ndebele, South", "South Ndebele"}, {"nbl", "nr"}},
        {{"Ndonga"}, {"ndo", "ng"}},
        {{"Neapolitan"}, {"nap"}},
        {{"Nepali"}, {"nep"}},
        {{"Newari", "Nepal Bhasa"}, {"new"}},
        {{"Nias"}, {"nia"}},
        {{"Niger-Kordofanian languages"}, {"nic"}},
        {{"Nilo-Saharan languages"}, {"ssa"}},
        {{"Niuean"}, {"niu"}},
        {{"Nogai"}, {"nog"}},
        {{"Norse, Old"}, {"non"}},
        {{"North American Indian languages"}, {"nai"}},
        {{"North Ndebele", "Ndebele, North"}, {"nde", "nd"}},
        {{"Northern Frisian"}, {"frr"}},
        {{"Northern Sami"}, {"se", "sme"}},
        {{"Norwegian"}, {"nor", "no"}},
        {{"Norwegian Bokmål", "Bokmål, Norwegian"}, {"nb", "nob"}},
        {{"Not applicable", "No linguistic content"}, {"zxx"}},
        {{"Nubian languages"}, {"nub"}},
        {{"Nuosu", "Sichuan Yi"}, {"ii", "iii"}},
        {{"Nyamwezi"}, {"nym"}},
        {{"Nyankole"}, {"nyn"}},
        {{"Nynorsk, Norwegian", "Norwegian Nynorsk"}, {"nno", "nn"}},
        {{"Nyoro"}, {"nyo"}},
        {{"Nzima"}, {"nzi"}},
        {{"Occitan (post 1500)"}, {"oci", "oc"}},
        {{"Official Aramaic (700-300 BCE)", "Imperial Aramaic (700-300 BCE)"}, {"arc"}},
        {{"Ojibwa"}, {"oj", "oji"}},
        {{"Old Slavonic", "Church Slavonic", "Old Bulgarian", "Church Slavic", "Old Church Slavonic"}, {"chu", "cu"}},
        {{"Oriya"}, {"ori"}},
        {{"Oromo"}, {"om", "orm"}},
        {{"Osage"}, {"osa"}},
        {{"Ossetian", "Ossetic"}, {"oss", "os"}},
        {{"Otomian languages"}, {"oto"}},
        {{"Pahlavi"}, {"pal"}},
        {{"Palauan"}, {"pau"}},
        {{"Pali"}, {"pli", "pi"}},
        {{"Pampanga", "Kapampangan"}, {"pam"}},
        {{"Pangasinan"}, {"pag"}},
        {{"Papiamento"}, {"pap"}},
        {{"Papuan languages"}, {"paa"}},
        {{"Pashto", "Pushto"}, {"ps", "pus"}},
        {{"Pedi", "Northern Sotho", "Sepedi"}, {"nso"}},
        {{"Persian"}, {"fas", "per", "fa"}},
        {{"Persian, Old (ca.600-400 B.C.)"}, {"peo"}},
        {{"Philippine languages"}, {"phi"}},
        {{"Phoenician"}, {"phn"}},
        {{"Pilipino", "Filipino"}, {"fil"}},
        {{"Pohnpeian"}, {"pon"}},
        {{"Polish"}, {"pol", "pl"}},
        {{"Portuguese"}, {"pt", "por"}},
        {{"Prakrit languages"}, {"pra"}},
        {{"Provençal, Old (to 1500);Occitan, Old (to 1500)"}, {"pro"}},
        {{"Punjabi", "Panjabi"}, {"pa", "pan"}},
        {{"Quechua"}, {"que", "qu"}},
        {{"Rajasthani"}, {"raj"}},
        {{"Rapanui"}, {"rap"}},
        {{"Reserved for local use"}, {"qaa-qtz"}},
        {{"Romance languages"}, {"roa"}},
        {{"Romansh"}, {"rm", "roh"}},
        {{"Romany"}, {"rom"}},
        {{"Rundi"}, {"rn", "run"}},
        {{"Russian"}, {"ru", "rus"}},
        {{"Salishan languages"}, {"sal"}},
        {{"Samaritan Aramaic"}, {"sam"}},
        {{"Sami languages"}, {"smi"}},
        {{"Samoan"}, {"sm", "smo"}},
        {{"Sandawe"}, {"sad"}},
        {{"Sango"}, {"sag", "sg"}},
        {{"Sanskrit"}, {"san", "sa"}},
        {{"Santali"}, {"sat"}},
        {{"Sardinian"}, {"sc", "srd"}},
        {{"Sasak"}, {"sas"}},
        {{"Scots"}, {"sco"}},
        {{"Scottish Gaelic", "Gaelic"}, {"gla", "gd"}},
        {{"Selkup"}, {"sel"}},
        {{"Semitic languages"}, {"sem"}},
        {{"Serbian"}, {"sr", "srp"}},
        {{"Serer"}, {"srr"}},
        {{"Shan"}, {"shn"}},
        {{"Shona"}, {"sn", "sna"}},
        {{"Sicilian"}, {"scn"}},
        {{"Sidamo"}, {"sid"}},
        {{"Sign Languages"}, {"sgn"}},
        {{"Siksika"}, {"bla"}},
        {{"Sindhi"}, {"snd", "sd"}},
        {{"Sinhala", "Sinhalese"}, {"sin", "si"}},
        {{"Sino-Tibetan languages"}, {"sit"}},
        {{"Siouan languages"}, {"sio"}},
        {{"Skolt Sami"}, {"sms"}},
        {{"Slave (Athapascan)"}, {"den"}},
        {{"Slavic languages"}, {"sla"}},
        {{"Slovak"}, {"slo", "sk", "slk"}},
        {{"Slovenian"}, {"sl", "slv"}},
        {{"Sogdian"}, {"sog"}},
        {{"Somali"}, {"so", "som"}},
        {{"Songhai languages"}, {"son"}},
        {{"Soninke"}, {"snk"}},
        {{"Sorbian languages"}, {"wen"}},
        {{"Sotho, Southern"}, {"sot"}},
        {{"South American Indian languages"}, {"sai"}},
        {{"Southern Altai"}, {"alt"}},
        {{"Southern Sami"}, {"sma"}},
        {{"Spanish", "Castilian"}, {"spa", "es"}},
        {{"Sranan Tongo"}, {"srn"}},
        {{"Standard Moroccan Tamazight"}, {"zgh"}},
        {{"Sukuma"}, {"suk"}},
        {{"Sumerian"}, {"sux"}},
        {{"Sundanese"}, {"sun", "su"}},
        {{"Susu"}, {"sus"}},
        {{"Swahili"}, {"swa"}},
        {{"Swati"}, {"ssw", "ss"}},
        {{"Swedish"}, {"sv", "swe"}},
        {{"Syriac"}, {"syr"}},
        {{"Tagalog"}, {"tgl", "tl"}},
        {{"Tahitian"}, {"ty", "tah"}},
        {{"Tai languages"}, {"tai"}},
        {{"Tajik"}, {"tgk", "tg"}},
        {{"Tamashek"}, {"tmh"}},
        {{"Tamil"}, {"ta", "tam"}},
        {{"Tatar"}, {"tt", "tat"}},
        {{"Telugu"}, {"tel", "te"}},
        {{"Tereno"}, {"ter"}},
        {{"Tetum"}, {"tet"}},
        {{"Thai"}, {"tha", "th"}},
        {{"Tibetan"}, {"bod", "tib", "bo"}},
        {{"Tigre"}, {"tig"}},
        {{"Tigrinya"}, {"ti", "tir"}},
        {{"Timne"}, {"tem"}},
        {{"Tiv"}, {"tiv"}},
        {{"Tlingit"}, {"tli"}},
        {{"Tok Pisin"}, {"tpi"}},
        {{"Tokelau"}, {"tkl"}},
        {{"Tonga (Nyasa)"}, {"tog"}},
        {{"Tonga (Tonga Islands)"}, {"ton", "to"}},
        {{"Tsimshian"}, {"tsi"}},
        {{"Tsonga"}, {"tso", "ts"}},
        {{"Tswana"}, {"tsn", "tn"}},
        {{"Tumbuka"}, {"tum"}},
        {{"Tupi languages"}, {"tup"}},
        {{"Turkish"}, {"tr", "tur"}},
        {{"Turkish, Ottoman (1500-1928)"}, {"ota"}},
        {{"Turkmen"}, {"tk", "tuk"}},
        {{"Tuvalu"}, {"tvl"}},
        {{"Tuvinian"}, {"tyv"}},
        {{"Twi"}, {"twi", "tw"}},
        {{"Udmurt"}, {"udm"}},
        {{"Ugaritic"}, {"uga"}},
        {{"Ukrainian"}, {"ukr", "uk"}},
        {{"Umbundu"}, {"umb"}},
        {{"Uncoded languages"}, {"mis"}},
        {{"Undetermined"}, {"und"}},
        {{"Upper Sorbian"}, {"hsb"}},
        {{"Urdu"}, {"urd", "ur"}},
        {{"Uyghur", "Uighur"}, {"uig", "ug"}},
        {{"Uzbek"}, {"uzb", "uz"}},
        {{"Vai"}, {"vai"}},
        {{"Venda"}, {"ven", "ve"}},
        {{"Vietnamese"}, {"vie", "vi"}},
        {{"Volapük"}, {"vo", "vol"}},
        {{"Votic"}, {"vot"}},
        {{"Wakashan languages"}, {"wak"}},
        {{"Walloon"}, {"wln", "wa"}},
        {{"Waray"}, {"war"}},
        {{"Washo"}, {"was"}},
        {{"Welsh"}, {"cy", "wel", "cym"}},
        {{"Western Frisian"}, {"fy", "fry"}},
        {{"Western Pahari languages", "Himachali languages"}, {"him"}},
        {{"Wolaitta", "Wolaytta"}, {"wal"}},
        {{"Wolof"}, {"wo", "wol"}},
        {{"Xhosa"}, {"xho", "xh"}},
        {{"Yakut"}, {"sah"}},
        {{"Yao"}, {"yao"}},
        {{"Yapese"}, {"yap"}},
        {{"Yiddish"}, {"ji", "yid"}},
        {{"Yoruba"}, {"yor", "yo"}},
        {{"Yupik languages"}, {"ypk"}},
        {{"Zande languages"}, {"znd"}},
        {{"Zapotec"}, {"zap"}},
        {{"Zenaga"}, {"zen"}},
        {{"Zhuang", "Chuang"}, {"zha", "za"}},
        {{"Zulu"}, {"zu", "zul"}},
        {{"Zuni"}, {"zun"}}
    }};
    
    bool does_tag_match_language(const string& language, const string& tag);
    const string_view& get_tag_language(const string& tag);
    const vector<string_view>& get_language_tags(const string& language);
}