/*   
 *   Matroska track setter  Copyright (C) 2023  Kyoya2
 *   
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *   
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *   
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#pragma once

#include <array>
#include <algorithm>

#include "Common.h"

struct LanguageDescriptor
{
    vector<string_view> language_names;
    vector<string_view> tags;
};

namespace MatroskaLanguageTags
{
    static string UNKNOWN_LANGUGAGE = "UNKNOWN";
    static const std::array<LanguageDescriptor, 487> language_tags{{
        {{"Abkhazian"}, {"ab", "abk"}},
        {{"Achinese"}, {"ace"}},
        {{"Acoli"}, {"ach"}},
        {{"Adangme"}, {"ada"}},
        {{"Adygei", "Adyghe"}, {"ady"}},
        {{"Afar"}, {"aa", "aar"}},
        {{"Afrihili"}, {"afh"}},
        {{"Afrikaans"}, {"af", "afr"}},
        {{"Afro-Asiatic languages"}, {"afa"}},
        {{"Ainu"}, {"ain"}},
        {{"Akan"}, {"ak", "aka"}},
        {{"Akkadian"}, {"akk"}},
        {{"Albanian"}, {"alb", "sq", "sqi"}},
        {{"Alemannic", "Alsatian", "Swiss German"}, {"gsw"}},
        {{"Aleut"}, {"ale"}},
        {{"Algonquian languages"}, {"alg"}},
        {{"Altaic languages"}, {"tut"}},
        {{"Amharic"}, {"am", "amh"}},
        {{"Angika"}, {"anp"}},
        {{"Apache languages"}, {"apa"}},
        {{"Arabic"}, {"ar", "ara"}},
        {{"Aragonese"}, {"an", "arg"}},
        {{"Arapaho"}, {"arp"}},
        {{"Arawak"}, {"arw"}},
        {{"Armenian"}, {"arm", "hy", "hye"}},
        {{"Aromanian", "Arumanian", "Macedo-Romanian"}, {"rup"}},
        {{"Artificial languages"}, {"art"}},
        {{"Assamese"}, {"as", "asm"}},
        {{"Asturian", "Asturleonese", "Bable", "Leonese"}, {"ast"}},
        {{"Athapascan languages"}, {"ath"}},
        {{"Australian languages"}, {"aus"}},
        {{"Austronesian languages"}, {"map"}},
        {{"Avaric"}, {"av", "ava"}},
        {{"Avestan"}, {"ae", "ave"}},
        {{"Awadhi"}, {"awa"}},
        {{"Aymara"}, {"ay", "aym"}},
        {{"Azerbaijani"}, {"az", "aze"}},
        {{"Balinese"}, {"ban"}},
        {{"Baltic languages"}, {"bat"}},
        {{"Baluchi"}, {"bal"}},
        {{"Bambara"}, {"bam", "bm"}},
        {{"Bamileke languages"}, {"bai"}},
        {{"Banda languages"}, {"bad"}},
        {{"Bantu languages"}, {"bnt"}},
        {{"Basa"}, {"bas"}},
        {{"Bashkir"}, {"ba", "bak"}},
        {{"Basque"}, {"baq", "eu", "eus"}},
        {{"Batak languages"}, {"btk"}},
        {{"Bedawiyet", "Beja"}, {"bej"}},
        {{"Belarusian"}, {"be", "bel"}},
        {{"Bemba"}, {"bem"}},
        {{"Bengali"}, {"ben"}},
        {{"Berber languages"}, {"ber"}},
        {{"Bhojpuri"}, {"bho"}},
        {{"Bihari languages"}, {"bh", "bih"}},
        {{"Bikol"}, {"bik"}},
        {{"Bilin", "Blin"}, {"byn"}},
        {{"Bini", "Edo"}, {"bin"}},
        {{"Bislama"}, {"bi", "bis"}},
        {{"Bliss", "Blissymbolics", "Blissymbols"}, {"zbl"}},
        {{"Bokmål, Norwegian", "Norwegian Bokmål"}, {"nb", "nob"}},
        {{"Bosnian"}, {"bos", "bs"}},
        {{"Braj"}, {"bra"}},
        {{"Breton"}, {"br", "bre"}},
        {{"Buginese"}, {"bug"}},
        {{"Bulgarian"}, {"bg", "bul"}},
        {{"Buriat"}, {"bua"}},
        {{"Burmese"}, {"bur", "my", "mya"}},
        {{"Caddo"}, {"cad"}},
        {{"Castilian", "Spanish"}, {"es", "spa"}},
        {{"Catalan", "Valencian"}, {"ca", "cat"}},
        {{"Caucasian languages"}, {"cau"}},
        {{"Cebuano"}, {"ceb"}},
        {{"Celtic languages"}, {"cel"}},
        {{"Central American Indian languages"}, {"cai"}},
        {{"Central Khmer"}, {"khm", "km"}},
        {{"Chagatai"}, {"chg"}},
        {{"Chamic languages"}, {"cmc"}},
        {{"Chamorro"}, {"ch", "cha"}},
        {{"Chechen"}, {"ce", "che"}},
        {{"Cherokee"}, {"chr"}},
        {{"Chewa", "Chichewa", "Nyanja"}, {"ny", "nya"}},
        {{"Cheyenne"}, {"chy"}},
        {{"Chibcha"}, {"chb"}},
        {{"Chinese"}, {"chi", "zh", "zho"}},
        {{"Chinook jargon"}, {"chn"}},
        {{"Chipewyan", "Dene Suline"}, {"chp"}},
        {{"Choctaw"}, {"cho"}},
        {{"Chuang", "Zhuang"}, {"za", "zha"}},
        {{"Church Slavic", "Church Slavonic", "Old Bulgarian", "Old Church Slavonic", "Old Slavonic"}, {"chu", "cu"}},
        {{"Chuukese"}, {"chk"}},
        {{"Chuvash"}, {"chv", "cv"}},
        {{"Classical Nepal Bhasa", "Classical Newari", "Old Newari"}, {"nwc"}},
        {{"Classical Syriac"}, {"syc"}},
        {{"Cook Islands Maori", "Rarotongan"}, {"rar"}},
        {{"Coptic"}, {"cop"}},
        {{"Cornish"}, {"cor", "kw"}},
        {{"Corsican"}, {"co", "cos"}},
        {{"Cree"}, {"cr", "cre"}},
        {{"Creek"}, {"mus"}},
        {{"Creoles and pidgins"}, {"crp"}},
        {{"Creoles and pidgins, English based"}, {"cpe"}},
        {{"Creoles and pidgins, French-based"}, {"cpf"}},
        {{"Creoles and pidgins, Portuguese-based"}, {"cpp"}},
        {{"Crimean Tatar", "Crimean Turkish"}, {"crh"}},
        {{"Croatian"}, {"hr", "hrv"}},
        {{"Cushitic languages"}, {"cus"}},
        {{"Czech"}, {"ces", "cs", "cze"}},
        {{"Dakota"}, {"dak"}},
        {{"Danish"}, {"da", "dan"}},
        {{"Dargwa"}, {"dar"}},
        {{"Delaware"}, {"del"}},
        {{"Dhivehi", "Divehi", "Maldivian"}, {"div", "dv"}},
        {{"Dimili", "Dimli", "Kirdki", "Kirmanjki", "Zaza", "Zazaki"}, {"zza"}},
        {{"Dinka"}, {"din"}},
        {{"Dogri"}, {"doi"}},
        {{"Dogrib"}, {"dgr"}},
        {{"Dravidian languages"}, {"dra"}},
        {{"Duala"}, {"dua"}},
        {{"Dutch", "Flemish"}, {"dut", "nl", "nld"}},
        {{"Dutch, Middle (ca.1050-1350)"}, {"dum"}},
        {{"Dyula"}, {"dyu"}},
        {{"Dzongkha"}, {"dz", "dzo"}},
        {{"Eastern Frisian"}, {"frs"}},
        {{"Efik"}, {"efi"}},
        {{"Egyptian (Ancient)"}, {"egy"}},
        {{"Ekajuk"}, {"eka"}},
        {{"Elamite"}, {"elx"}},
        {{"English"}, {"en", "eng"}},
        {{"English, Middle (1100-1500)"}, {"enm"}},
        {{"English, Old (ca.450-1100)"}, {"ang"}},
        {{"Erzya"}, {"myv"}},
        {{"Esperanto"}, {"eo", "epo"}},
        {{"Estonian"}, {"est", "et"}},
        {{"Ewe"}, {"ee", "ewe"}},
        {{"Ewondo"}, {"ewo"}},
        {{"Fang"}, {"fan"}},
        {{"Fanti"}, {"fat"}},
        {{"Faroese"}, {"fao", "fo"}},
        {{"Fijian"}, {"fij", "fj"}},
        {{"Filipino", "Pilipino"}, {"fil"}},
        {{"Finnish"}, {"fi", "fin"}},
        {{"Finno-Ugrian languages"}, {"fiu"}},
        {{"Fon"}, {"fon"}},
        {{"French"}, {"fr", "fra", "fre"}},
        {{"French, Middle (ca.1400-1600)"}, {"frm"}},
        {{"French, Old (842-ca.1400)"}, {"fro"}},
        {{"Friulian"}, {"fur"}},
        {{"Fulah"}, {"ff", "ful"}},
        {{"Ga"}, {"gaa"}},
        {{"Gaelic", "Scottish Gaelic"}, {"gd", "gla"}},
        {{"Galibi Carib"}, {"car"}},
        {{"Galician"}, {"gl", "glg"}},
        {{"Ganda"}, {"lug"}},
        {{"Gayo"}, {"gay"}},
        {{"Gbaya"}, {"gba"}},
        {{"Geez"}, {"gez"}},
        {{"Georgian"}, {"geo", "ka", "kat"}},
        {{"German"}, {"de", "deu", "ger"}},
        {{"German, Low", "Low German", "Low Saxon", "Saxon, Low"}, {"nds"}},
        {{"German, Middle High (ca.1050-1500)"}, {"gmh"}},
        {{"German, Old High (ca.750-1050)"}, {"goh"}},
        {{"Germanic languages"}, {"gem"}},
        {{"Gikuyu", "Kikuyu"}, {"ki", "kik"}},
        {{"Gilbertese"}, {"gil"}},
        {{"Gondi"}, {"gon"}},
        {{"Gorontalo"}, {"gor"}},
        {{"Gothic"}, {"got"}},
        {{"Grebo"}, {"grb"}},
        {{"Greek, Ancient (to 1453)"}, {"grc"}},
        {{"Greek, Modern (1453-)"}, {"ell", "gre"}},
        {{"Greenlandic", "Kalaallisut"}, {"kal", "kl"}},
        {{"Guarani"}, {"gn", "grn"}},
        {{"Gujarati"}, {"gu", "guj"}},
        {{"Gwich'in"}, {"gwi"}},
        {{"Haida"}, {"hai"}},
        {{"Haitian", "Haitian Creole"}, {"hat", "ht"}},
        {{"Hausa"}, {"ha", "hau"}},
        {{"Hawaiian"}, {"haw"}},
        {{"Hebrew"}, {"he", "heb"}},
        {{"Herero"}, {"her", "hz"}},
        {{"Hiligaynon"}, {"hil"}},
        {{"Himachali languages", "Western Pahari languages"}, {"him"}},
        {{"Hindi"}, {"hi", "hin"}},
        {{"Hiri Motu"}, {"hmo", "ho"}},
        {{"Hittite"}, {"hit"}},
        {{"Hmong", "Mong"}, {"hmn"}},
        {{"Hungarian"}, {"hu", "hun"}},
        {{"Hupa"}, {"hup"}},
        {{"Iban"}, {"iba"}},
        {{"Icelandic"}, {"ice", "is", "isl"}},
        {{"Ido"}, {"ido", "io"}},
        {{"Igbo"}, {"ibo", "ig"}},
        {{"Ijo languages"}, {"ijo"}},
        {{"Iloko"}, {"ilo"}},
        {{"Imperial Aramaic (700-300 BCE)", "Official Aramaic (700-300 BCE)"}, {"arc"}},
        {{"Inari Sami"}, {"smn"}},
        {{"Indic languages"}, {"inc"}},
        {{"Indo-European languages"}, {"ine"}},
        {{"Indonesian"}, {"id", "ind"}},
        {{"Ingush"}, {"inh"}},
        {{"Interlingua (International Auxiliary Language Association)"}, {"ia", "ina"}},
        {{"Interlingue", "Occidental"}, {"ie", "ile"}},
        {{"Inuktitut"}, {"iku", "iu"}},
        {{"Inupiaq"}, {"ik", "ipk"}},
        {{"Iranian languages"}, {"ira"}},
        {{"Irish"}, {"ga", "gle"}},
        {{"Irish, Middle (900-1200)"}, {"mga"}},
        {{"Irish, Old (to 900)"}, {"sga"}},
        {{"Iroquoian languages"}, {"iro"}},
        {{"Italian"}, {"it", "ita"}},
        {{"Japanese"}, {"ja", "jpn"}},
        {{"Javanese"}, {"jav", "jv"}},
        {{"Jingpho", "Kachin"}, {"kac"}},
        {{"Judeo-Arabic"}, {"jrb"}},
        {{"Judeo-Persian"}, {"jpr"}},
        {{"Kabardian"}, {"kbd"}},
        {{"Kabyle"}, {"kab"}},
        {{"Kalmyk", "Oirat"}, {"xal"}},
        {{"Kamba"}, {"kam"}},
        {{"Kannada"}, {"kan", "kn"}},
        {{"Kanuri"}, {"kau", "kr"}},
        {{"Kapampangan", "Pampanga"}, {"pam"}},
        {{"Kara-Kalpak"}, {"kaa"}},
        {{"Karachay-Balkar"}, {"krc"}},
        {{"Karelian"}, {"krl"}},
        {{"Karen languages"}, {"kar"}},
        {{"Kashmiri"}, {"kas", "ks"}},
        {{"Kashubian"}, {"csb"}},
        {{"Kawi"}, {"kaw"}},
        {{"Kazakh"}, {"kaz", "kk"}},
        {{"Khasi"}, {"kha"}},
        {{"Khoisan languages"}, {"khi"}},
        {{"Khotanese", "Sakan"}, {"kho"}},
        {{"Kimbundu"}, {"kmb"}},
        {{"Kinyarwanda"}, {"kin", "rw"}},
        {{"Kirghiz", "Kyrgyz"}, {"kir", "ky"}},
        {{"Klingon", "tlhIngan-Hol"}, {"tlh"}},
        {{"Komi"}, {"kom", "kv"}},
        {{"Kongo"}, {"kg", "kon"}},
        {{"Konkani"}, {"kok"}},
        {{"Korean"}, {"ko", "kor"}},
        {{"Kosraean"}, {"kos"}},
        {{"Kpelle"}, {"kpe"}},
        {{"Kru languages"}, {"kro"}},
        {{"Kuanyama", "Kwanyama"}, {"kj", "kua"}},
        {{"Kumyk"}, {"kum"}},
        {{"Kurdish"}, {"ku", "kur"}},
        {{"Kurukh"}, {"kru"}},
        {{"Kutenai"}, {"kut"}},
        {{"Ladino"}, {"lad"}},
        {{"Lahnda"}, {"lah"}},
        {{"Lamba"}, {"lam"}},
        {{"Land Dayak languages"}, {"day"}},
        {{"Lao"}, {"lao", "lo"}},
        {{"Latin"}, {"la", "lat"}},
        {{"Latvian"}, {"lav", "lv"}},
        {{"Letzeburgesch", "Luxembourgish"}, {"lb", "ltz"}},
        {{"Lezghian"}, {"lez"}},
        {{"Limburgan", "Limburger", "Limburgish"}, {"li", "lim"}},
        {{"Lingala"}, {"lin", "ln"}},
        {{"Lithuanian"}, {"lit", "lt"}},
        {{"Lojban"}, {"jbo"}},
        {{"Lower Sorbian"}, {"dsb"}},
        {{"Lozi"}, {"loz"}},
        {{"Luba-Katanga"}, {"lu", "lub"}},
        {{"Luba-Lulua"}, {"lua"}},
        {{"Luiseno"}, {"lui"}},
        {{"Lule Sami"}, {"smj"}},
        {{"Lunda"}, {"lun"}},
        {{"Luo (Kenya and Tanzania)"}, {"luo"}},
        {{"Lushai"}, {"lus"}},
        {{"Macedonian"}, {"mac", "mk", "mkd"}},
        {{"Madurese"}, {"mad"}},
        {{"Magahi"}, {"mag"}},
        {{"Maithili"}, {"mai"}},
        {{"Makasar"}, {"mak"}},
        {{"Malagasy"}, {"mg", "mlg"}},
        {{"Malay"}, {"may", "msa"}},
        {{"Malayalam"}, {"mal", "ml"}},
        {{"Maltese"}, {"mlt", "mt"}},
        {{"Manchu"}, {"mnc"}},
        {{"Mandar"}, {"mdr"}},
        {{"Mandingo"}, {"man"}},
        {{"Manipuri"}, {"mni"}},
        {{"Manobo languages"}, {"mno"}},
        {{"Manx"}, {"glv", "gv"}},
        {{"Maori"}, {"mao", "mi", "mri"}},
        {{"Mapuche", "Mapudungun"}, {"arn"}},
        {{"Marathi"}, {"mar", "mr"}},
        {{"Mari"}, {"chm"}},
        {{"Marshallese"}, {"mah", "mh"}},
        {{"Marwari"}, {"mwr"}},
        {{"Masai"}, {"mas"}},
        {{"Mayan languages"}, {"myn"}},
        {{"Mende"}, {"men"}},
        {{"Mi'kmaq", "Micmac"}, {"mic"}},
        {{"Minangkabau"}, {"min"}},
        {{"Mirandese"}, {"mwl"}},
        {{"Mohawk"}, {"moh"}},
        {{"Moksha"}, {"mdf"}},
        {{"Moldavian", "Moldovan", "Romanian"}, {"mo", "ron", "rum"}},
        {{"Mon-Khmer languages"}, {"mkh"}},
        {{"Mongo"}, {"lol"}},
        {{"Mongolian"}, {"mn", "mon"}},
        {{"Montenegrin"}, {"cnr"}},
        {{"Mossi"}, {"mos"}},
        {{"Multiple languages"}, {"mul"}},
        {{"Munda languages"}, {"mun"}},
        {{"N'Ko"}, {"nqo"}},
        {{"Nahuatl languages"}, {"nah"}},
        {{"Nauru"}, {"na", "nau"}},
        {{"Navaho", "Navajo"}, {"nav", "nv"}},
        {{"Ndebele, North", "North Ndebele"}, {"nd", "nde"}},
        {{"Ndebele, South", "South Ndebele"}, {"nbl", "nr"}},
        {{"Ndonga"}, {"ndo", "ng"}},
        {{"Neapolitan"}, {"nap"}},
        {{"Nepal Bhasa", "Newari"}, {"new"}},
        {{"Nepali"}, {"nep"}},
        {{"Nias"}, {"nia"}},
        {{"Niger-Kordofanian languages"}, {"nic"}},
        {{"Nilo-Saharan languages"}, {"ssa"}},
        {{"Niuean"}, {"niu"}},
        {{"No linguistic content", "Not applicable"}, {"zxx"}},
        {{"Nogai"}, {"nog"}},
        {{"Norse, Old"}, {"non"}},
        {{"North American Indian languages"}, {"nai"}},
        {{"Northern Frisian"}, {"frr"}},
        {{"Northern Sami"}, {"se", "sme"}},
        {{"Northern Sotho", "Pedi", "Sepedi"}, {"nso"}},
        {{"Norwegian Nynorsk", "Nynorsk, Norwegian"}, {"nn", "nno"}},
        {{"Norwegian"}, {"no", "nor"}},
        {{"Nubian languages"}, {"nub"}},
        {{"Nuosu", "Sichuan Yi"}, {"ii", "iii"}},
        {{"Nyamwezi"}, {"nym"}},
        {{"Nyankole"}, {"nyn"}},
        {{"Nyoro"}, {"nyo"}},
        {{"Nzima"}, {"nzi"}},
        {{"Occitan (post 1500)"}, {"oc", "oci"}},
        {{"Ojibwa"}, {"oj", "oji"}},
        {{"Oriya"}, {"ori"}},
        {{"Oromo"}, {"om", "orm"}},
        {{"Osage"}, {"osa"}},
        {{"Ossetian", "Ossetic"}, {"os", "oss"}},
        {{"Otomian languages"}, {"oto"}},
        {{"Pahlavi"}, {"pal"}},
        {{"Palauan"}, {"pau"}},
        {{"Pali"}, {"pi", "pli"}},
        {{"Pangasinan"}, {"pag"}},
        {{"Panjabi", "Punjabi"}, {"pa", "pan"}},
        {{"Papiamento"}, {"pap"}},
        {{"Papuan languages"}, {"paa"}},
        {{"Pashto", "Pushto"}, {"ps", "pus"}},
        {{"Persian"}, {"fa", "fas", "per"}},
        {{"Persian, Old (ca.600-400 B.C.)"}, {"peo"}},
        {{"Philippine languages"}, {"phi"}},
        {{"Phoenician"}, {"phn"}},
        {{"Pohnpeian"}, {"pon"}},
        {{"Polish"}, {"pl", "pol"}},
        {{"Portuguese"}, {"por", "pt"}},
        {{"Prakrit languages"}, {"pra"}},
        {{"Provençal, Old (to 1500);Occitan, Old (to 1500)"}, {"pro"}},
        {{"Quechua"}, {"qu", "que"}},
        {{"Rajasthani"}, {"raj"}},
        {{"Rapanui"}, {"rap"}},
        {{"Reserved for local use"}, {"qaa-qtz"}},
        {{"Romance languages"}, {"roa"}},
        {{"Romansh"}, {"rm", "roh"}},
        {{"Romany"}, {"rom"}},
        {{"Rundi"}, {"rn", "run"}},
        {{"Russian"}, {"ru", "rus"}},
        {{"Salishan languages"}, {"sal"}},
        {{"Samaritan Aramaic"}, {"sam"}},
        {{"Sami languages"}, {"smi"}},
        {{"Samoan"}, {"sm", "smo"}},
        {{"Sandawe"}, {"sad"}},
        {{"Sango"}, {"sag", "sg"}},
        {{"Sanskrit"}, {"sa", "san"}},
        {{"Santali"}, {"sat"}},
        {{"Sardinian"}, {"sc", "srd"}},
        {{"Sasak"}, {"sas"}},
        {{"Scots"}, {"sco"}},
        {{"Selkup"}, {"sel"}},
        {{"Semitic languages"}, {"sem"}},
        {{"Serbian"}, {"sr", "srp"}},
        {{"Serer"}, {"srr"}},
        {{"Shan"}, {"shn"}},
        {{"Shona"}, {"sn", "sna"}},
        {{"Sicilian"}, {"scn"}},
        {{"Sidamo"}, {"sid"}},
        {{"Sign Languages"}, {"sgn"}},
        {{"Siksika"}, {"bla"}},
        {{"Sindhi"}, {"sd", "snd"}},
        {{"Sinhala", "Sinhalese"}, {"si", "sin"}},
        {{"Sino-Tibetan languages"}, {"sit"}},
        {{"Siouan languages"}, {"sio"}},
        {{"Skolt Sami"}, {"sms"}},
        {{"Slave (Athapascan)"}, {"den"}},
        {{"Slavic languages"}, {"sla"}},
        {{"Slovak"}, {"sk", "slk", "slo"}},
        {{"Slovenian"}, {"sl", "slv"}},
        {{"Sogdian"}, {"sog"}},
        {{"Somali"}, {"so", "som"}},
        {{"Songhai languages"}, {"son"}},
        {{"Soninke"}, {"snk"}},
        {{"Sorbian languages"}, {"wen"}},
        {{"Sotho, Southern"}, {"sot"}},
        {{"South American Indian languages"}, {"sai"}},
        {{"Southern Altai"}, {"alt"}},
        {{"Southern Sami"}, {"sma"}},
        {{"Sranan Tongo"}, {"srn"}},
        {{"Standard Moroccan Tamazight"}, {"zgh"}},
        {{"Sukuma"}, {"suk"}},
        {{"Sumerian"}, {"sux"}},
        {{"Sundanese"}, {"su", "sun"}},
        {{"Susu"}, {"sus"}},
        {{"Swahili"}, {"swa"}},
        {{"Swati"}, {"ss", "ssw"}},
        {{"Swedish"}, {"sv", "swe"}},
        {{"Syriac"}, {"syr"}},
        {{"Tagalog"}, {"tgl", "tl"}},
        {{"Tahitian"}, {"tah", "ty"}},
        {{"Tai languages"}, {"tai"}},
        {{"Tajik"}, {"tg", "tgk"}},
        {{"Tamashek"}, {"tmh"}},
        {{"Tamil"}, {"ta", "tam"}},
        {{"Tatar"}, {"tat", "tt"}},
        {{"Telugu"}, {"te", "tel"}},
        {{"Tereno"}, {"ter"}},
        {{"Tetum"}, {"tet"}},
        {{"Thai"}, {"th", "tha"}},
        {{"Tibetan"}, {"bo", "bod", "tib"}},
        {{"Tigre"}, {"tig"}},
        {{"Tigrinya"}, {"ti", "tir"}},
        {{"Timne"}, {"tem"}},
        {{"Tiv"}, {"tiv"}},
        {{"Tlingit"}, {"tli"}},
        {{"Tok Pisin"}, {"tpi"}},
        {{"Tokelau"}, {"tkl"}},
        {{"Tonga (Nyasa)"}, {"tog"}},
        {{"Tonga (Tonga Islands)"}, {"to", "ton"}},
        {{"Tsimshian"}, {"tsi"}},
        {{"Tsonga"}, {"ts", "tso"}},
        {{"Tswana"}, {"tn", "tsn"}},
        {{"Tumbuka"}, {"tum"}},
        {{"Tupi languages"}, {"tup"}},
        {{"Turkish"}, {"tr", "tur"}},
        {{"Turkish, Ottoman (1500-1928)"}, {"ota"}},
        {{"Turkmen"}, {"tk", "tuk"}},
        {{"Tuvalu"}, {"tvl"}},
        {{"Tuvinian"}, {"tyv"}},
        {{"Twi"}, {"tw", "twi"}},
        {{"Udmurt"}, {"udm"}},
        {{"Ugaritic"}, {"uga"}},
        {{"Uighur", "Uyghur"}, {"ug", "uig"}},
        {{"Ukrainian"}, {"uk", "ukr"}},
        {{"Umbundu"}, {"umb"}},
        {{"Uncoded languages"}, {"mis"}},
        {{"Undetermined"}, {"und"}},
        {{"Upper Sorbian"}, {"hsb"}},
        {{"Urdu"}, {"ur", "urd"}},
        {{"Uzbek"}, {"uz", "uzb"}},
        {{"Vai"}, {"vai"}},
        {{"Venda"}, {"ve", "ven"}},
        {{"Vietnamese"}, {"vi", "vie"}},
        {{"Volapük"}, {"vo", "vol"}},
        {{"Votic"}, {"vot"}},
        {{"Wakashan languages"}, {"wak"}},
        {{"Walloon"}, {"wa", "wln"}},
        {{"Waray"}, {"war"}},
        {{"Washo"}, {"was"}},
        {{"Welsh"}, {"cy", "cym", "wel"}},
        {{"Western Frisian"}, {"fry", "fy"}},
        {{"Wolaitta", "Wolaytta"}, {"wal"}},
        {{"Wolof"}, {"wo", "wol"}},
        {{"Xhosa"}, {"xh", "xho"}},
        {{"Yakut"}, {"sah"}},
        {{"Yao"}, {"yao"}},
        {{"Yapese"}, {"yap"}},
        {{"Yiddish"}, {"ji", "yid"}},
        {{"Yoruba"}, {"yo", "yor"}},
        {{"Yupik languages"}, {"ypk"}},
        {{"Zande languages"}, {"znd"}},
        {{"Zapotec"}, {"zap"}},
        {{"Zenaga"}, {"zen"}},
        {{"Zulu"}, {"zu", "zul"}},
        {{"Zuni"}, {"zun"}}
    }};
    
    bool does_tag_match_language(const string& language, const string& tag);
    string get_tag_language(const string& tag);
    const vector<string_view>& get_language_tags(const string& language);
}